//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renta_devolucion
    {
        public int id { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<System.DateTime> fecha_devolucion { get; set; }
        public Nullable<System.DateTime> fecha_renta { get; set; }
        public Nullable<double> monto_dia { get; set; }
        public Nullable<int> total_dias { get; set; }
        public string comentario { get; set; }
        public string estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
